let mongoose = require('mongoose');
let Schema = mongoose.Schema;
let uuidv4 = require('uuid/v4')();

let guard = new mongoose.Schema({
    //blockId
    blockName: {type: Schema.Types.ObjectId, ref:'blocks', default: null},
    //uniquely generated by system
    uid: {type: String, default: uuidv4, unique: true},
    //alternative value is girls
    /*type: {type: String, default: 'boys', required: true},
    block: {type: String, default: 'Q', required: true},*/
    //guard name
    name: {type: String, default: null, required: true},
    session: {type: String, default: null, required: true, /*unique: true*/},
    /*
    * duty value either morning or evening
    * */
    duty: {type: String, default: 'morning', required: true}
});

module.exports = mongoose.model('guards', guard);