let mongoose = require('mongoose');
let Schema = mongoose.Schema;
let uuidv4 = require('uuid/v4')();

let room = new mongoose.Schema({
    uid: {type: String, default: uuidv4},
    //blockid for easy reference
    blockName: {type: Schema.Types.ObjectId, default: null, ref:"blocks"},
    //generated by combination of data
    roomId : {type: String, default: 'B6Q333', unique: true},
    //room number
    num: {type: Number, default: 333, required: true},
    //alternative value is girls
    type: {type: String, default: 'boys', required: true},
    block: {type: String, default: 'Q', required: true},
    //number of bed
    bed: {type: Number, default: 6, required: true},
    //room clean request id
    cleanRequestId: {type: Schema.Types.ObjectId, ref: 'cleans', default: null},
    //count of student register for that room
    //count: {type: Number, default: 0, max: Number(this.roomId[1])}
});


module.exports = mongoose.model('rooms', room);